### PR TITLE
Printing filename from project directory.

### PR DESCRIPTION
**Pull request by NanduTej**
@mboekhold The new PR instead of https://github.com/Zarad1993/dyc/pull/32

### CODE REVIEW

**Comment by mboekhold** [comment]
run `black method.py`

**Comment by NanduTej** [comment]
Done

> run `black method.py`

**Comment by mboekhold** [comment]
Thank you @NanduTej !

**Comment by NanduTej** [comment]
Thank you @mboekhold ! :smile:

**Pull request merged**
