### PR TITLE
Implement Class Docstrings as per Issue #5 #67

### PR DESCRIPTION
**Pull request by calkerns**
Reference Issue: #5 Classes Docstrings

This was a Joint effort between @AshirGuptash and I.

**Key Changes**

Add _classes.py_ file
Add preliminary script-based unit test suite for classes
Add **--test** flag in DYC for automated testing purposes
Apply _Black_ formatter on all files to ensure consistency
The main body of this is in regards to creating a _ClassBuilder_ object to handle adding docstrings to the start of classes. Currently, it only supports adding details on inheritance to the docstring, but can be further be modified to handle other variables such as \_\_init\_\_ parameters or class attributes.

### CODE REVIEW

**Comment by Zarad1993** [comment]
Thank you @calkerns for submitting a pull request!

**Review by Zarad1993 — CHANGES_REQUESTED** [review]
Could you check the `README` to be documenting the latest changes you are adding?

Thank you so much, again!

**Comment by calkerns** [comment]
Hi @Zarad1993, you're welcome; thank you for your response! Yes, you are so right; documentation is needed! My colleague and I will get to work on that tomorrow.

**Comment by AshirGuptash** [comment]
Hi @Zarad1993 , we updated the README with the documentation for the ClassBuilder options as well as clarified the --test flag (renamed it to --skip-confirm) because all it does is bypass the popup editor in the confirmation phase. This has also been added under the _Usage_ section of the README as it is also useful for the end-user, not just for testing purposes.

Let us know if we should make any other changes!

**Review by Zarad1993 — CHANGES_REQUESTED** [review]
Why do we need the `automated_class_tests` directory? 🤔 
I might be missing something.
Like `tests/automated_class_tests/user_input/class_test_1.in`. Not sure what that does or it needs to be in the PR

**Comment by Zarad1993** [comment]
Hey guys 👋 , just want to let you know tests are failing.

**Comment by AshirGuptash** [comment]
Hi @Zarad1993 , my bad about tests failing, I am trying a few things with regards to pytest and am aware of this issue, sorry about that. In regards to the `automated_class_tests` directory, our original goal of this was to create an easy alternative to pytest for piping user input into DYC and then automatically testing it against oracle files. Currently I am trying to integrate this into the Pytest framework in order to keep consistency.

**Comment by Zarad1993** [comment]
I love it, man! Let me know when it's ready for review. Keep it up, guys!

If you guys have LinkedIn profiles, I'm happy to connect https://linkedin.com/in/zarad1993 . I'd like to give you guys a shoutout

**Comment by AshirGuptash** [comment]
Sounds good, also happy to connect on LinkedIn!

**Comment by AshirGuptash** [comment]
Hey @Zarad1993 , we repurposed the `automated_class_tests` folder by converting the bash-script-based test suite into a Pytest item that helps to test methods that deal with file I/O. However, we have currently commented this portion out due to issues with running on Python2.7, but we think this would be more appropriate to address in the updated test suite as part of issue #2. We also removed the `automated_class_tests` folder as it is no longer necessary, but have included a subfolder in `tests` named `test_case_files` to handle the file I/O from Pytest.

We hope this will suffice!

**Review by Zarad1993 — APPROVED** [review]
Nice work, thanks folks!

**Comment by calkerns** [comment]
@Zarad1993 I would be happy to connect on LinkedIn as well! Thank you for offering and for working with us on this PR!

**Pull request merged**
